/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 cyber_truck.glb --transform
Author: Arion Digital (https://sketchfab.com/andrewswihart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-truck-1f5174e78fd549a8be8f7ae622caa223
Title: Cyber Truck
*/

import React, { useRef,useLayoutEffect } from "react";
import { useGLTF,useScroll } from "@react-three/drei";
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

export function Cyber_truck(props) {
  const { nodes, materials } = useGLTF("./models/cyber_truck-transformed.glb");
   const truck =  useRef()
  const scroll = useScroll()
  const tl = useRef()

  useFrame((state, delta)=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useLayoutEffect(()=> {
    tl.current = gsap.timeline({defaults: {duration: 2, ease: 'power1.inOut'}})

    tl.current
    .to(truck.current.rotation, {y: -1}, 2)
    .to(truck.current.position, {x: 1}, 2)

    .to(truck.current.rotation, {y: 1}, 6)
    .to(truck.current.position, {x: -1}, 6)

    .to(truck.current.rotation, {y: 0}, 11)
    .to(truck.current.rotation, {x: 1}, 11)
    .to(truck.current.position, {x: 0}, 11)

    .to(truck.current.rotation, {y: 0}, 13)
    .to(truck.current.rotation, {x: -1}, 13)
    .to(truck.current.position, {x: 0}, 13)

    .to(truck.current.rotation, {y: 0}, 16)
    .to(truck.current.rotation, {x: 0}, 16)
    .to(truck.current.position, {x: 0}, 16)

    .to(truck.current.rotation, {y: 0}, 20)
    .to(truck.current.rotation, {x: 0}, 20)
    .to(truck.current.position, {x: 0}, 20)

  },[])

  return (
    <group {...props} dispose={null} ref={truck}>
      <group position={[-2.3, -0.5, 0]} rotation={[0,0,0]} scale={0.007}>
        <group position={[0, 0, 0]}>
          <mesh
            geometry={nodes.updated_tire001_Tire_0.geometry}
            material={materials.Tire}
          >
            <meshPhysicalMaterial
              color="#020204"
              roughnes={1}
              reflectivity={0.45}
            />
          </mesh>

          <mesh
            geometry={nodes.updated_tire001_Rims_0.geometry}
            material={materials.Rims}
            castShadow
          >
            <meshPhysicalMaterial
              color="black"
              roughness={0}
              metalness={1}
              reflectivity={0.9}
            />
          </mesh>

          <mesh
            geometry={nodes.updated_tire001_Undercarag_0.geometry}
            material={materials.Undercarag}
          />
          <mesh
            geometry={nodes.updated_tire001_Body_0.geometry}
            material={materials.Body}
            castShadow
          >
            <meshStandardMaterial
              color="#aaa"
              roughness={0.18}
              metalness={1}
              reflectivity={0.4}
              iridescence={0}
              iridescenceIOR={0}
              iridescenceThicknessRange={[100, 1000]}
            />
          </mesh>
          <mesh
            geometry={nodes.updated_tire001_Headlights_0.geometry}
            material={materials.Headlights}
            castShadow
          >
          </mesh>
          <mesh
            geometry={nodes.updated_tire001_Glass_0.geometry}
            material={materials.Glass}
            castShadow
          >
            <meshPhysicalMaterial
              color="black"
              roughness={0}
              emissive={"black"}
              clearcoat={0}
              reflectivity={0}
              metalness={1}
              iridescence={0}
              iridescenceIOR={1}
              iridescenceThicknessRange={[100, 1000]}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/cyber_truck-transformed.glb");
