/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 model.glb --transform
Author: HardBread (https://sketchfab.com/Alexey..Tverdohleb)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/ase-interstellar-low-poly-c638f55aad814156a9a9561980a78eac
Title: СASE / Interstellar (Low-poly)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("./models/model-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2.5, 0.37]} rotation={[0, -0.6, 0]} scale={2.5}   >
      <spotLight intensity={0.3} position={[-30, 30, 50]} angle={0.2} penumbra={1} castShadow ={true} />
      <spotLight intensity={0.3} position={[-25, -30, 50]} angle={0.2} penumbra={1} castShadow ={true}/>
      <spotLight intensity={0.2} position={[30, -30, 50]} angle={0.2} penumbra={1} castShadow ={true} />
      <ambientLight intensity={1}  />
        <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.TARSCASE}
        rotation={[-Math.PI / 2, 0, 0]} />


      </group>
    </group>
  );
}

useGLTF.preload("./models/model-transformed.glb");
